build: false

environment:
  matrix:
    - CHANNEL: stable
    - CHANNEL: beta
    - CHANNEL: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain %CHANNEL%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

test_script:
  - cargo build

notifications:
  - provider: Webhook
    url: https://bors2-test.herokuapp.com/webhook/appveyor/alexcrichton/bors2
